### ISSUE TITLE
Assertion failure when excluding DC relay fingerprints from noise_weight

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#415]
The TS can exclude a DC from a collection round by not including the DC relay fingerprint in the TS `noise_weight` config. However, when doing so, the data collector fails with the following backtrace.

```
2017-08-08 12:55:10 1502222110.352781 [privcount-dc] [INFO] Tor version is 0.3.0.8 (git-2a0827686f6daed3)
2017-08-08 12:55:10 1502222110.353116 [privcount-dc] [INFO] Tor PrivCount version is 1.1.0
2017-08-08 12:55:10 1502222110.353347 [privcount-dc] [WARNING] Tally Server did not provide a noise weight for our fingerprint C170AE5A886C5A09D6D1CF5CF284653632EEF25D in noise weight config {u'D53793315E290D250E9AFC431A4C9068A1E53C98': 1.0}, we will not count in this round.
2017-08-08 12:55:10 1502222110.353503 [privcount-dc] [INFO] Stopping collection, no events received.
2017-08-08 12:55:10 1502222110.353703 [privcount-dc] [INFO] Waiting for next PrivCount collection to start
2017-08-08 12:55:10 1502222110.353799 [privcount-dc] [INFO] Open control connection with remote: 127.0.0.1:9056 local: 127.0.0.1:33184 quit: (no error).
2017-08-08 12:55:10 1502222110.353886 [privcount-dc] [INFO] Stopping collection, no events received.
2017-08-08 12:55:10 1502222110.354096 [privcount-dc] [INFO] Waiting for next PrivCount collection to start
Unhandled Error
Traceback (most recent call last):
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/privcount/protocol.py", line 2032, in lineReceived
    'fingerprint')
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/privcount/protocol.py", line 1425, in setDiscoveredValue
    if not getattr(self.factory, set_function_name)(value):
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/privcount/data_collector.py", line 880, in set_fingerprint
    self.generate_noise()
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/privcount/data_collector.py", line 620, in generate_noise
    self._stop_secure_counters(counts_are_valid=False)
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/privcount/data_collector.py", line 568, in _stop_secure_counters
    counts = self.secure_counters.detach_counts()
  File "/home/rjansen/test/venv/lib/python2.7/site-packages/privcount/counter.py", line 1693, in detach_counts
    assert not self.is_noise_pending
exceptions.AssertionError: 

2017-08-08 12:55:10 1502222110.357002 [privcount-dc] [INFO] Disconnected control connection with remote: 127.0.0.1:9056 lost: .
```

**Comment by teor2345** [comment]
The root cause of this error is that _stop_secure_counters() should not call detach_counts() unless counts_are_valid.

The fix passes our standard integration tests, and the alternate injector test where the hard-coded relay fingerprint has no noise weight (the "missing fingerprint failure case").

There is no test where some relays participate, and some do not. I opened #428 in the next release for that.
