### ISSUE TITLE
TypeError comparing datetime to int

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#474]
When attempting to run `privcount/tools/compute_fractional_position_weights`, I get the following error:

```
running weights privcount version 2.0.0 (protocol PRIVCOUNT-100, git-(no revision))
using consensuses '2018-01-04-01-00-00-consensus' and fingerprints '['09FA8B4F665AD65D2C2A49870F1AA3BA8811E449', '068308AD070849A71B8C1DB06C2509E82C40B908', '335746A6DEB684FABDF3FC5835C3898F05C5A5A8', '363F42695F2DD825DA5A4E6ABF3FBDFCFD1E9AE2', 'B6718125C43ECA2E5011B3C681BB6638617A9686', 'C6B3546CC6BCCB649FEC82D348D464554BC6323D', '12B80ABF019354A9D25EE8BE85EB3C0AD8F7DFC1', 'DE684E6C6B7773B8BE74B4D941E4178988E15E26', '4B1E3276137AD12DCCEBE354EA11C1E47F804F67', 'C170AE5A886C5A09D6D1CF5CF284653632EEF25D', 'A5945077E0D35729F8E2920A54BE12A0058B403E', '0DA9BD201766EDB19F57F49F1A013A8A5432C008', 'D53793315E290D250E9AFC431A4C9068A1E53C98', '11EAB5C9137906EF7E6A32365C4B37613698E647', '91516595837183D9ECD1318D00723A8676F4731C', '1A4488A367D89D0EFDA88116059FEBCACF0F508A', '98D10461F6EDF13780D20D7E402E67F40C5ADBD9']'
Traceback (most recent call last):
  File "/Users/rob/Projects/privcount/privcount/tools/compute_fractional_position_weights", line 520, in <module>
    sys.exit(main())
  File "/Users/rob/Projects/privcount/privcount/tools/compute_fractional_position_weights", line 186, in main
    result = process_consensus(params)
  File "/Users/rob/Projects/privcount/privcount/tools/compute_fractional_position_weights", line 227, in process_consensus
    guard_frac, middle_frac, exit_frac, hsdir2_frac, hsdir2_svc_frac, hsdir3_frac, hsdir3_svc_frac, intro_frac, rend2_frac, rend3_frac = get_fractional_weights(consensus_path, prints)
  File "/Users/rob/Projects/privcount/privcount/tools/compute_fractional_position_weights", line 302, in get_fractional_weights
    net_status.valid_after)
  File "/Users/rob/Projects/privcount/privcount/tools/compute_fractional_position_weights", line 126, in hsdir_v3_descriptor_store_overlap
    assert valid_after >= 0
TypeError: can't compare datetime.datetime to int
```

Changing line 126 from:
```
assert valid_after >= 0
```

to
```
assert valid_after.year >= 0
```

fixed the problem for me (but there might be a better way than just checking the year).

**Comment by teor2345** [comment]
I pushed a fix to master, it compares with datetime.min instead.
